# Spark assignment

Taratukhin Oleg, C41323

Initial env setup:

In [91]:
import pyspark
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pandas as pd
from pathlib import Path

spark = SparkSession.builder \
    .appName("itmo spark assignment") \
    .master("local[*]") \
    .getOrCreate()

spark

In [88]:
!cd data && ls
!rm -rf results/task1/

PATH_TO_DATA = Path("data/")
PATH_TO_RESULTS = Path("results/task1/")

followers.parquet              posts_api.json
followers_posts_api_final.json posts_likes.parquet
followers_posts_likes.parquet

Utilities:

In [92]:
def save_as_json(df: pyspark.sql.dataframe.DataFrame, name: str):
    df.write \
        .format("json") \
        .save(str(PATH_TO_RESULTS / name))

def get_top_col(df: pyspark.sql.dataframe.DataFrame, col: str, limit=20):
    return df \
        .orderBy(df[col].count.desc()) \
        .limit(limit)
        
def get_top_likes(df: pyspark.sql.dataframe.DataFrame, limit=20):
    return get_top_col(df, "likes", limit)
    
def get_top_likes(df: pyspark.sql.dataframe.DataFrame, limit=20):
    return get_top_col(df, "comments", limit)
    
def get_top_likes(df: pyspark.sql.dataframe.DataFrame, limit=20):
    return get_top_col(df, "reposts", limit)

## Task 1

Display the top 20 liked, commented, reposted posts by number (for all datasets with posts)

In [93]:
posts = spark \
    .read \
    .json(str(PATH_TO_DATA / "posts_api.json"))

posts \
    .limit(10) \
    .toPandas()

,attachments,comments,copy_history,copyright,date,from_id,geo,id,key,likes,marked_as_ads,owner_id,post_source,post_type,reposts,signer_id,text,unavailable,views
0,None,"(1, 0, True)","[([Row(album=None, audio=None, doc=None, link=...",None,1418838050,-94,None,17274,-94_17274,"(1, 1, 12, 0)",0,-94,"(None, iphone, api)",post,"(5, 0)",None,,None,None
1,"[(None, None, None, None, None, (791d86f8b302d...","(1, 0, True)",None,None,1418812223,-94,None,17273,-94_17273,"(1, 1, 7, 0)",0,-94,"(None, None, vk)",post,"(3, 0)",None,[Технологические брокеры объединят науку и биз...,None,None
2,None,"(1, 0, True)","[([Row(album=None, audio=None, doc=None, link=...",None,1418932825,-94,None,17313,-94_17313,"(1, 1, 14, 0)",0,-94,"(None, None, vk)",post,"(4, 0)",None,,None,None
3,"[(None, None, None, None, None, (912f07ffb75c8...","(1, 0, True)",None,None,1418929134,-94,None,17301,-94_17301,"(1, 1, 30, 0)",0,-94,"(None, None, vk)",post,"(17, 0)",None,"Дорогие друзья, мы открываем новую рубрику, в ...",None,None
4,"[(None, None, None, None, None, (48de0a7227ce0...","(1, 2, True)",None,None,1418922045,-94,None,17295,-94_17295,"(1, 1, 10, 0)",0,-94,"(None, None, vk)",post,"(0, 0)",None,[Первый выпуск Молодежного коворкинг-центра Ун...,None,None
5,"[(None, None, None, None, None, (01786517929f7...","(1, 3, True)",None,None,1418906160,-94,None,17293,-94_17293,"(1, 1, 51, 0)",0,-94,"(None, None, vk)",post,"(9, 0)",None,[Александр Ишевский о новых продуктах и востре...,None,None
6,"[(None, None, None, None, None, (108e8d387cd05...","(1, 27, True)",None,None,1418893664,-94,None,17277,-94_17277,"(1, 1, 16, 0)",0,-94,"(None, None, vk)",post,"(0, 0)",None,Для желающих увидеть большую пресс-конференцию...,None,None
7,"[(None, None, None, None, None, (c243da0b8a371...","(1, 0, True)",None,None,1418889630,-94,None,17276,-94_17276,"(1, 1, 4, 0)",0,-94,"(None, None, vk)",post,"(0, 0)",None,[Профессоры Пауль Урбах и Юрки Сааринен расска...,None,None
8,"[(None, None, None, None, None, (f5a6642309dea...","(1, 23, True)",None,None,1418997628,-94,None,17326,-94_17326,"(1, 1, 68, 0)",0,-94,"(None, None, vk)",post,"(34, 0)",None,"Подготовка к праздникам уже в самом разгаре, а...",None,None
9,"[(None, None, None, None, None, (b9c7483cdcc2b...","(1, 0, True)",None,None,1418993264,-94,None,17323,-94_17323,"(1, 1, 1, 0)",0,-94,"(None, None, vk)",post,"(1, 0)",None,[Татьяна Богомазова: какой должна быть информа...,None,None

In [94]:
followers_posts = spark \
    .read \
    .json(str(PATH_TO_DATA / "followers_posts_api_final.json"))

followers_posts \
    .limit(10) \
    .toPandas()

,attachments,comments,copy_history,copyright,date,final_post,from_id,geo,id,is_pinned,key,likes,owner_id,post_source,post_type,reposts,signer_id,text,unavailable,views
0,"[(None, None, None, None, None, None, None, No...","(0, 0, True)",None,None,1550165023,None,87449,None,3316,None,87449_3316,"(1, 1, 6, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,"Я люблю Вас. Я вчера, даже, хотел Вам это сказ...",None,"(428,)"
1,"[(None, None, None, None, None, None, (fe02668...","(0, 0, True)",None,None,1553774858,None,87449,None,3318,None,87449_3318,"(1, 1, 11, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,call me by your name ♡,None,"(477,)"
2,"[(None, None, None, None, None, None, (c25cda8...","(0, 0, True)",None,None,1555602008,None,87449,None,3320,None,87449_3320,"(1, 1, 10, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,🦋,None,"(419,)"
3,"[(None, None, None, None, None, None, None, No...","(0, 0, True)",None,None,1558105050,None,87449,None,3322,None,87449_3322,"(1, 1, 8, 0)",87449,"(None, None, iphone, api, None)",post,"(1, 0)",None,"Браво,Юра !",None,"(442,)"
4,"[(None, None, None, None, None, None, (7758fb4...","(0, 0, True)",None,None,1559301729,None,87449,None,3324,None,87449_3324,"(1, 1, 8, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,🕊,None,"(425,)"
5,"[(None, None, None, None, None, None, (666dd69...","(0, 0, True)",None,None,1564088944,None,87449,None,3325,None,87449_3325,"(1, 1, 10, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,Самый неприятный побочный эффект взросления дл...,None,"(301,)"
6,"[(None, None, None, None, None, None, (06ab977...","(0, 0, True)",None,None,1565162341,None,87449,None,3326,None,87449_3326,"(1, 1, 6, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,🔅,None,"(309,)"
7,"[(None, None, None, None, None, None, (74fdfc9...","(0, 0, True)",None,None,1566293696,None,87449,None,3327,None,87449_3327,"(1, 1, 9, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,Пекло.Пушка.Вышка.\nЧёртов гений Тарантино. Лю...,None,"(366,)"
8,"[(None, None, None, None, None, None, (02804b0...","(0, 0, True)",None,None,1571221102,None,87449,None,3329,None,87449_3329,"(1, 1, 0, 0)",87449,"(None, None, iphone, api, None)",post,"(0, 0)",None,,None,"(139,)"
9,"[(None, None, None, None, None, None, (a88e65c...","(1, 1, True)",None,None,1559647730,None,94494,None,11752,None,94494_11752,"(1, 1, 17, 0)",94494,"(None, None, None, vk, None)",post,"(0, 0)",None,"Тот неловкий момент, когда прилетел из унылого...",None,"(594,)"

### Top likes

In [75]:
top_likes = get_top_likes(posts)

save_as_json(top_likes, "task1_posts_likes.json")

top_likes.toPandas()[["text"]]

                                                 text
0   Стесняешься петь любимую песню в лаборатории? ...
1   У нас для вас две хорошие новости: \nПервая - ...
2   Настали снежные холода, самое время согреться ...
3   [Пригласи друзей на [club89993971|открытие Год...
4   Ура! Нас 20 000! Спасибо, что вы с нами! А в б...
5   Добро пожаловать в КиберПитер 2019 — город, в ...
6   [Университет ИТМО стал шестикратным чемпионом ...
7   Я ПОСТУПИЛ В УНИВЕРСИТЕТ ИТМО! \n\nМесяцы подг...
8   WE ARE THE CHAMPIONS! СЕДЬМАЯ ПОБЕДА УНИВЕРСИТ...
9   Студенты, сегодня ваш день! И мы уже подготови...
10  Ура! Кубок ICPC снова у России! Поздравляем ко...
11  ITMO.GO! Я поступил в Университет ИТМО! \n \nЕ...
12  Команда студентов НИУ ИТМО снова завоевала зва...
13  Хочешь поздравить [club16824047|Чемпионов РПЛ]...
14  К концу года мы дали старт миссии: #сессиявИТМ...
15  #ExamsAreComing #университет #ИТМО #ITMO #univ...
16  [Я участвую в велопрогулке с ректором Универси...
17  [Билет на GEEK PICNIC за репост]\n\n20-21 июня...
18  А вы хотите на Geek Picnic?\n\n25 и 26 июня в ...
19                   Начало конкурса Мистер ИТМО 2013

In [76]:
top_likes = get_top_likes(posts)

save_as_json(top_likes, "task1_followers_likes.json")

top_likes.toPandas()[["text"]]

                                                 text
0   Стесняешься петь любимую песню в лаборатории? ...
1   У нас для вас две хорошие новости: \nПервая - ...
2   Настали снежные холода, самое время согреться ...
3   [Пригласи друзей на [club89993971|открытие Год...
4   Ура! Нас 20 000! Спасибо, что вы с нами! А в б...
5   Добро пожаловать в КиберПитер 2019 — город, в ...
6   [Университет ИТМО стал шестикратным чемпионом ...
7   Я ПОСТУПИЛ В УНИВЕРСИТЕТ ИТМО! \n\nМесяцы подг...
8   WE ARE THE CHAMPIONS! СЕДЬМАЯ ПОБЕДА УНИВЕРСИТ...
9   Студенты, сегодня ваш день! И мы уже подготови...
10  Ура! Кубок ICPC снова у России! Поздравляем ко...
11  ITMO.GO! Я поступил в Университет ИТМО! \n \nЕ...
12  Команда студентов НИУ ИТМО снова завоевала зва...
13  Хочешь поздравить [club16824047|Чемпионов РПЛ]...
14  К концу года мы дали старт миссии: #сессиявИТМ...
15  #ExamsAreComing #университет #ИТМО #ITMO #univ...
16  [Я участвую в велопрогулке с ректором Универси...
17  [Билет на GEEK PICNIC за репост]\n\n20-21 июня...
18  А вы хотите на Geek Picnic?\n\n25 и 26 июня в ...
19                   Начало конкурса Мистер ИТМО 2013

### Top comments

In [79]:
top_comments = get_top_comments(posts)

save_as_json(top_comments, "task1_posts_comments.json")

top_comments.toPandas()[["text"]]

                                                 text
0   Студенты, сегодня ваш день! И мы уже подготови...
1   Друзья, а давайте немного поиграем? \n\nМы при...
2   Upd: розыгрыш завершен, благодарим всех участн...
3   Все знают, что в этом году занятия начинаются ...
4   18 мая состоится четвертая велопрогулка с рект...
5   15 российских вузов получат субсидии в размере...
6   Информация по аварийной ситуации в здании унив...
7   ОФИЦИАЛЬНО: СЕССИЯ УЖЕ В ИТМО! \n\nИ как всегд...
8   ДОБРО ПОЖАЛОВАТЬ В УНИВЕРСИТЕТ ИТМО! 💙🎉\n \nРа...
9   Дорогие абитуриенты, присоединяйтесь к нашему ...
10  Уважаемые студенты! Проводится социологический...
11  Внимание! Розыгрыш призов!\n\nВ эту среду сост...
12  Science Valentine’s Day — это день самых гикан...
13  Информация по аварийной ситуации в здании унив...
14
15  Роботы пишут стихи, обыгрывают человека в Го, ...
16  Опубликованы приказы о зачислении с 1 сентября...
17  Пришла пора узнать ответ на главный вопрос: КА...
18  Придумай название студенческому спортивному кл...
19  В рамках реализации программы по повышению меж...

In [81]:
top_comments = get_top_comments(followers_posts)

save_as_json(top_comments, "task1_followers_comments.json")

top_comments.toPandas()[["text"]]

                                                 text
0                                   Гости у bera vine
1                                                Live
2                                          Погнали💥💥💥
3                                           Звоночки💥
4   Ребят,как и говорили,мы все купили📚🧩🎲\nЕще раз...
5                                     Всем приветик💋🖤
6                                           Погнали☄️
7                                 Сегодня будет мощно
8                              В конце будут сигны🤪❤💪
9                                Bera vine в сборе💥💥💥
10                                        Полетели🔥🔥🔥
11     Готовим,розыгрываем сигны,проводим лайк тайм💥❤
12         Идем искать и кормить бездомных друзей 💥💥💥
13                          Красим т.Валю с Курска💥💥💥
14                                               Live
15                                          Звонки💥💥💥
16                               Звоним по номерам💥💥💥
17                                               Live
18       ВСЕМ ПРИВЕТ,ГОТОВЛЮ И ПРОВОЖУ ЛАЙК ТАЙМ❤❤❤💥💥
19                                          Встречины

### Top reposted

In [84]:
top_reposts = get_top_reposts(posts)

save_as_json(top_reposts, "task1_posts_reposts.json")

top_reposts.toPandas()[["text"]]

                                                 text
0   Настали снежные холода, самое время согреться ...
1   Ура! Нас 20 000! Спасибо, что вы с нами! А в б...
2   Стесняешься петь любимую песню в лаборатории? ...
3   8 октября пропал без вести студент Вашего ВУЗа...
4   [Университет ИТМО стал шестикратным чемпионом ...
5   Команда студентов НИУ ИТМО снова завоевала зва...
6   #ExamsAreComing #университет #ИТМО #ITMO #univ...
7   У нас для вас две хорошие новости: \nПервая - ...
8   В преддверии выпускного ITMOLiVE [club94359346...
9   Подарок всем студентам в первый день весны! Во...
10  Я ПОСТУПИЛ В УНИВЕРСИТЕТ ИТМО! \n\nМесяцы подг...
11                   Начало конкурса Мистер ИТМО 2013
12  Добро пожаловать в КиберПитер 2019 — город, в ...
13  [Билет на GEEK PICNIC за репост]\n\n20-21 июня...
14  🎄Выходные дни в январе 2015 года🎄\n\nВ среду 3...
15  МЫ СНОВА АБСОЛЮТНЫЕ ЧЕМПИОНЫ МИРА ПО ПРОГРАММИ...
16  [TechTrends Expo разыгрывает бесплатные билеты...
17  [Выходные дни в ноябре]\n\nВнимание! В соответ...
18  [Выиграй билеты на "Бал роботов"]\n\nСо 2 янва...
19  Лето. Жара. Петербург! Что еще нужно для полно...

In [85]:
top_reposts = get_top_reposts(followers_posts)

save_as_json(top_reposts, "task1_followers_reposts.json")

top_reposts.toPandas()[["text"]]

                                                 text
0   Нашли корги. Бегал по Октябрьской набережной п...
1        🔥 НОВИНКА / [club36856627|Skid] / IMISSYOU 🔥
2   Инновационная система \nПервая инновационная п...
3   УВЕДОМЛЕНИЕ в расчетный центр \n \n Довожу до ...
4   От 20$ в день из ВК!\nПредставляю вам полность...
5   Ты знаешь чего я хочу?\n– Всего.\n– Ну, это во...
6   Зоя Звиняцковская ФБ\nпростите, но я должна за...
7   ОРЗЕГА! МАЙГУБА! СЕГЕЖА!\n"...Меньше трех неде...
8
9
10  Любовь долготерпит, милосердствует, любовь не ...
11  [club74902570|More Dwine] produces quality roy...
12  Дорогие все. У меня есть возможность пообщатьс...
13  #лучшиепредставителичеловечества\nСпасибо вам ...
14  Многие ждали этого видоса, представление препо...
15  #лучшиепредставителичеловечества в субботу хос...
16  Привет биологам! \nLifetime opportunity! \n\nМ...
17  Друзья, вышло продолжение нашей истории о лесн...
18  ‼SOS‼СРОЧНО‼SOS‼\n\nСанкт-Петербург.\n\n🐱Сегод...
19  #лучшиепредставителичеловечества у нас совсем ...